version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
